CREATE TABLE NODE(
  XPOS INT,
  YPOS INT,
  FLOOR INT,
  ISHIDDEN BOOLEAN,
  ENABLED BOOLEAN DEFAULT TRUE,
  TYPE VARCHAR(100),
  NAME VARCHAR(100),
  ROOMNUM VARCHAR(100) UNIQUE,
  PRIMARY KEY(XPOS, YPOS, FLOOR)
);

CREATE TABLE EDGE(
  XPOS1 INT,
  YPOS1 INT,
  FLOOR1 INT,
  XPOS2 INT,
  YPOS2 INT,
  FLOOR2 INT,
  CONSTRAINT fkXPOS1 FOREIGN KEY (XPOS1, YPOS1, FLOOR1) REFERENCES NODE(XPOS, YPOS, FLOOR),
  CONSTRAINT fkXPOS2 FOREIGN KEY (XPOS2, YPOS2, FLOOR2) REFERENCES NODE(XPOS, YPOS, FLOOR)
);

CREATE TABLE PROFESSIONAL(
  ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  FIRSTNAME VARCHAR(100),
  LASTNAME VARCHAR(100),
  TYPE VARCHAR(100),
  SPTYPE VARCHAR(100),
  DEPARTMENT VARCHAR(100),
  SPDEPARTMENT VARCHAR(100)
);

CREATE TABLE PROLOCATION(
  PROID INT,
  XPOS INT,
  YPOS INT,
  FLOOR INT,
  CONSTRAINT fkProID FOREIGN KEY (PROID) REFERENCES PROFESSIONAL(ID),
  CONSTRAINT fkLoc FOREIGN KEY (XPOS, YPOS, FLOOR) REFERENCES NODE(XPOS, YPOS, FLOOR),
  PRIMARY KEY (PROID, XPOS, YPOS, FLOOR)
);

CREATE TABLE ADMIN(
  ID INTEGER PRIMARY KEY,
  FIRSTNAME VARCHAR(100),
  LASTNAME VARCHAR(100),
  USERNAME VARCHAR(100),
  PASSWORD VARCHAR(200)
);

CREATE TABLE SERVICE(
  ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  NAME VARCHAR(100),
  TYPE VARCHAR(100),
  XPOS INT,
  YPOS INT,
  FLOOR INT,
  CONSTRAINT fkSerLoc FOREIGN KEY (XPOS, YPOS, FLOOR) REFERENCES NODE(XPOS, YPOS, FLOOR)
);

CREATE TABLE DECODELANGUAGE(
  ENGLISH VARCHAR(100) PRIMARY KEY,
  SPANISH VARCHAR(100)
)