INSERT INTO APP.ADMIN (FIRSTNAME, LASTNAME, USERNAME, PASSWORD) VALUES ('Jason', 'Ashton', 'Jason', '$2a$10$MyXFwAYccDvY6B8zXDYDrOldaF0kBrPI/ybyUXCOhC0.i7o7qaCBu');
INSERT INTO APP.DECODELANGUAGE (ENGLISH, SPANISH) VALUES ('Doctor', 'Doctor/a');
INSERT INTO APP.DECODELANGUAGE (ENGLISH, SPANISH) VALUES ('Nurse', 'Enfermero/a');
INSERT INTO APP.DECODELANGUAGE (ENGLISH, SPANISH) VALUES ('Cardiology', 'Cardiología');
INSERT INTO APP.DECODELANGUAGE (ENGLISH, SPANISH) VALUES ('Allergic Diseases', 'Enfermedades alérgicas');
INSERT INTO APP.DECODELANGUAGE (ENGLISH, SPANISH) VALUES ('Doctor', 'Doctor/a');
