DROP TABLE EDGE;
DROP TABLE PROFESSIONAL;
DROP TABLE NODE;
DROP TABLE ADMIN;

CREATE TABLE NODE(
  XPOS INT,
  YPOS INT,
  FLOOR INT,
  ISHIDDEN BOOLEAN,
  ENABLED BOOLEAN DEFAULT TRUE,
  TYPE VARCHAR(100),
  NAME VARCHAR(100),
  ROOMNUM VARCHAR(100),
  PRIMARY KEY(XPOS, YPOS, FLOOR)
);

CREATE TABLE EDGE(
  XPOS1 INT,
  YPOS1 INT,
  FLOOR1 INT,
  XPOS2 INT,
  YPOS2 INT,
  FLOOR2 INT,
  CONSTRAINT fkXPOS1 FOREIGN KEY (XPOS1, YPOS1, FLOOR1) REFERENCES NODE(XPOS, YPOS, FLOOR),
  CONSTRAINT fkXPOS2 FOREIGN KEY (XPOS2, YPOS2, FLOOR2) REFERENCES NODE(XPOS, YPOS, FLOOR)
);

CREATE TABLE PROFESSIONAL(
  ID VARCHAR(100) PRIMARY KEY,
  XPOS INT,
  YPOS INT,
  FLOOR INT,
  FIRSTNAME VARCHAR(100),
  LASTNAME VARCHAR(100),
  TYPE VARCHAR(100),
  FOREIGN KEY (XPOS, YPOS, FLOOR) REFERENCES NODE(XPOS, YPOS, FLOOR)
);

CREATE TABLE ADMIN(
  ID INTEGER PRIMARY KEY,
  FIRSTNAME VARCHAR(100),
  LASTNAME VARCHAR(100),
  USERNAME VARCHAR(100),
  PASSWORD VARCHAR(200)
);

INSERT INTO ADMIN (ID, FIRSTNAME, LASTNAME, USERNAME, PASSWORD) VALUES (1, 'Jason', 'Ashton', 'Jason', '$2a$10$MyXFwAYccDvY6B8zXDYDrOldaF0kBrPI/ybyUXCOhC0.i7o7qaCBu');